window.WANHUA_POI_DATA = [
  {
    "id": "ihg_001",
    "map_label_name": "InterContinental 台北洲際酒店",
    "name_zh": "InterContinental 台北洲際酒店",
    "name_en": "InterContinental Taipei",
    "name_ja": "インターコンチネンタル台北",
    "primary_category": "其他設施",
    "subcategory": "飯店",
    "business_type": "hotel",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=InterContinental+Taipei",
    "address_zh": "台北市信義區新仁里忠孝東路四段535號",
    "phone": "店家未提供",
    "opening_hours": "24H front desk",
    "near_mrt": "國父紀念館站",
    "notes": "以台北洲際酒店為起點，步行即可串連大巨蛋、松菸與信義商圈，是探索周邊的住宿據點。",
    "source_status": "center",
    "source_url": "",
    "is_active": true,
    "display_order": 1,
    "walk_10min_from_hotel": true,
    "notes_zh": "以台北洲際酒店為起點，步行即可串連大巨蛋、松菸與信義商圈，是探索周邊的住宿據點。",
    "notes_en": "A convenient home base for exploring Taipei Dome, Songshan Cultural and Creative Park, and the Xinyi shopping district, all within easy reach of the hotel.",
    "notes_ja": "台北ドーム、松山文創園区、信義ショッピングエリアへ出かけやすい、周辺散策の拠点として便利なホテルです。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:43:53.912Z"
  },
  {
    "map_label_name": "臺北大巨蛋",
    "name_zh": "臺北大巨蛋",
    "name_en": "Taipei Dome",
    "name_ja": "台北ドーム",
    "primary_category": "景點",
    "subcategory": "商圈",
    "business_type": "attraction",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0424367,121.55950659999999",
    "address_zh": "110臺北市信義區忠孝東路四段515號",
    "phone": "02 2722 8811",
    "opening_hours": "24 小時營業",
    "near_mrt": "國父紀念館站",
    "notes": "臺北大巨蛋是信義區大型室內場館，適合觀賽、看演唱會，也能順遊周邊商場與餐飲。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0424367,121.55950659999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_002",
    "display_order": 2,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:43:57.942Z",
    "notes_zh": "臺北大巨蛋是信義區大型室內場館，適合觀賽、看演唱會，也能順遊周邊商場與餐飲。",
    "notes_en": "Taipei Dome is a major indoor venue in Xinyi, ideal for baseball games, concerts, and events, with shopping and dining options nearby.",
    "notes_ja": "信義区にある大型屋内施設で、野球観戦やコンサート、各種イベントに便利です。周辺にはショッピングや食事の選択肢もあります。"
  },
  {
    "map_label_name": "PRESERVE 遠東GARDEN CITY 大巨蛋店",
    "name_zh": "PRESERVE 遠東GARDEN CITY 大巨蛋店",
    "name_en": "PRESERVE Taipei Dome",
    "name_ja": "PRESERVE Taipei Dome",
    "primary_category": "餐飲",
    "subcategory": "早餐|午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "早餐",
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0430378,121.5596193",
    "address_zh": "110臺北市信義區忠孝東路四段515號",
    "phone": "02 2761 3365",
    "opening_hours": "09:00 – 20:00",
    "near_mrt": "國父紀念館站",
    "notes": "主打酪梨與健康輕食的餐廳，適合早午餐、輕食或想吃清爽餐點時造訪。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0430378,121.5596193",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_003",
    "display_order": 3,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:01.807Z",
    "notes_zh": "主打酪梨與健康輕食的餐廳，適合早午餐、輕食或想吃清爽餐點時造訪。",
    "notes_en": "A health-focused restaurant known for avocado dishes and lighter fare, suitable for brunch, a casual lunch, or a refreshing meal near Taipei Dome.",
    "notes_ja": "アボカド料理や軽めのメニューで知られるヘルシー志向のレストランです。ブランチや軽いランチ、さっぱりしたお食事におすすめです。"
  },
  {
    "map_label_name": "紫木槿韓餐酒館(遠東Garden City 大巨蛋店)",
    "name_zh": "紫木槿韓餐酒館(遠東Garden City 大巨蛋店)",
    "name_en": "Zihmujin Taipei Dome Branch",
    "name_ja": "Zihmujin Taipei Dome Branch",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0416275,121.55952979999999",
    "address_zh": "110臺北市信義區忠孝東路四段515號",
    "phone": "02 2766 9905",
    "opening_hours": "11:00 – 00:00",
    "near_mrt": "國父紀念館站",
    "notes": "結合韓式料理與餐酒館氛圍，適合晚餐聚餐、賽後小酌或朋友聚會。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0416275,121.55952979999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_004",
    "display_order": 4,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:05.535Z",
    "notes_zh": "結合韓式料理與餐酒館氛圍，適合晚餐聚餐、賽後小酌或朋友聚會。",
    "notes_en": "A Korean dining and bar concept with a lively atmosphere, well suited for dinner gatherings, drinks after an event, or a casual meal with friends.",
    "notes_ja": "韓国料理とバーの雰囲気を楽しめるお店です。夕食の集まりやイベント後の一杯、友人とのカジュアルなお食事に向いています。"
  },
  {
    "map_label_name": "湊湊火鍋•茶憩 大巨蛋店",
    "name_zh": "湊湊火鍋•茶憩 大巨蛋店",
    "name_en": "湊湊火鍋•茶憩 遠東GARDEN CITY大巨蛋店",
    "name_ja": "湊湊火鍋•茶憩 遠東GARDEN CITY大巨蛋店",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐|宵夜",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.041811499999998,121.5603733",
    "address_zh": "110臺北市信義區忠孝東路四段515號, 遠東GardenCity, 1F",
    "phone": "02 2756 6986",
    "opening_hours": "11:00 – 01:00",
    "near_mrt": "國父紀念館站",
    "notes": "火鍋與茶飲結合的聚餐選擇，營業到深夜，適合看完活動後續攤用餐。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.041811499999998,121.5603733",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_005",
    "display_order": 5,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:09.186Z",
    "notes_zh": "火鍋與茶飲結合的聚餐選擇，營業到深夜，適合看完活動後續攤用餐。",
    "notes_en": "A popular hot pot restaurant combining hearty broths with tea drinks, open late for guests looking for a relaxed meal after an event.",
    "notes_ja": "火鍋とお茶を組み合わせた人気店です。夜遅くまで営業しており、イベント後にゆっくり食事をしたい時にも便利です。"
  },
  {
    "map_label_name": "捷運國父紀念館站(忠孝)",
    "name_zh": "捷運國父紀念館站(忠孝)",
    "name_en": "MRT Sun Yat-Sen Memorial Hall Sta.(Zhongxiao)",
    "name_ja": "捷運国父紀念館站",
    "primary_category": "交通",
    "subcategory": "捷運站",
    "business_type": "transport",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.041470399999998,121.5590141",
    "address_zh": "110台灣臺北市信義區",
    "phone": "店家未提供",
    "opening_hours": "",
    "near_mrt": "國父紀念館站",
    "notes": "距離大巨蛋最近的捷運站之一，從飯店或場館移動到台北各區都很方便。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.041470399999998,121.5590141",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_006",
    "display_order": 6,
    "notes_zh": "距離大巨蛋最近的捷運站之一，從飯店或場館移動到台北各區都很方便。",
    "notes_en": "One of the closest MRT stations to Taipei Dome, offering convenient access from the hotel and easy connections to the rest of Taipei.",
    "notes_ja": "台北ドームに近いMRT駅のひとつで、ホテルや会場からの移動、台北市内各エリアへの乗り継ぎに便利です。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:12.830Z"
  },
  {
    "map_label_name": "松山文創園區",
    "name_zh": "松山文創園區",
    "name_en": "Songshan Cultural and Creative Park",
    "name_ja": "松山文創園区",
    "primary_category": "景點",
    "subcategory": "商圈",
    "business_type": "attraction",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0438366,121.5606383",
    "address_zh": "11072臺北市信義區光復南路133號",
    "phone": "02 2765 1388",
    "opening_hours": "08:00 – 22:00",
    "near_mrt": "國父紀念館站",
    "notes": "由老菸廠改造的文創園區，集結展覽、設計商店、綠地與餐飲，適合散步拍照。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0438366,121.5606383",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_007",
    "display_order": 7,
    "notes_zh": "由老菸廠改造的文創園區，集結展覽、設計商店、綠地與餐飲，適合散步拍照。",
    "notes_en": "A former tobacco factory transformed into a cultural park, featuring exhibitions, design shops, green spaces, cafes, and photogenic walking paths.",
    "notes_ja": "かつてのたばこ工場を活用した文化複合施設です。展示、デザインショップ、緑地、カフェがあり、散策や写真撮影にもおすすめです。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:16.377Z"
  },
  {
    "map_label_name": "國父紀念館",
    "name_zh": "國父紀念館",
    "name_en": "National Dr. Sun Yat-Sen Memorial Hall",
    "name_ja": "国立国父紀念館",
    "primary_category": "景點",
    "subcategory": "古蹟",
    "business_type": "attraction",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.041378299999998,121.5575216",
    "address_zh": "110臺北市信義區仁愛路四段505號",
    "phone": "02 2758 8008",
    "opening_hours": "09:00 – 18:00",
    "near_mrt": "國父紀念館站",
    "notes": "台北代表性紀念館與城市廣場，可看展覽、儀隊交接，也適合順路散步。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.041378299999998,121.5575216",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_008",
    "display_order": 8,
    "notes_zh": "台北代表性紀念館與城市廣場，可看展覽、儀隊交接，也適合順路散步。",
    "notes_en": "A landmark memorial hall and public plaza where guests can visit exhibitions, watch the guard-changing ceremony, and enjoy a relaxed walk.",
    "notes_ja": "台北を代表する記念館と広場です。展示見学や衛兵交代式の見学、周辺の散策をゆったり楽しめます。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:20.365Z"
  },
  {
    "map_label_name": "青花驕麻辣鍋 台北光復南店",
    "name_zh": "青花驕麻辣鍋 台北光復南店",
    "name_en": "Chin Hua Jiao Taipei Guangfu South Branch",
    "name_ja": "Chin Hua Jiao Taipei Guangfu South Branch",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0436277,121.5574946",
    "address_zh": "106臺北市大安區光復南路100號",
    "phone": "02 8772 0659",
    "opening_hours": "11:30 – 01:00",
    "near_mrt": "國父紀念館站",
    "notes": "麻辣鍋香氣濃郁、適合多人聚餐，距離大巨蛋不遠，是晚餐與宵夜的熱門選擇。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0436277,121.5574946",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_009",
    "display_order": 9,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:24.276Z",
    "notes_zh": "麻辣鍋香氣濃郁、適合多人聚餐，距離大巨蛋不遠，是晚餐與宵夜的熱門選擇。",
    "notes_en": "A well-known spicy hot pot restaurant with rich, aromatic broths, popular for group dinners near Taipei Dome.",
    "notes_ja": "香り豊かな麻辣火鍋で知られる人気店です。台北ドーム周辺でのグループディナーに向いています。"
  },
  {
    "map_label_name": "gonnaPLUS地中海健康旗艦餐廳",
    "name_zh": "gonnaPLUS地中海健康旗艦餐廳",
    "name_en": "gonnaPLUS",
    "name_ja": "gonnaPLUS",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0435187,121.561639",
    "address_zh": "110臺北市信義區光復南路133號松山文創園區生態池畔旁",
    "phone": "02 2769 2885",
    "opening_hours": "11:30 – 20:30",
    "near_mrt": "國父紀念館站",
    "notes": "主打地中海風格與健康餐點，鄰近松菸，適合想吃均衡料理或清爽聚餐的人。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0435187,121.561639",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_010",
    "display_order": 10,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:27.876Z",
    "notes_zh": "主打地中海風格與健康餐點，鄰近松菸，適合想吃均衡料理或清爽聚餐的人。",
    "notes_en": "A Mediterranean-inspired restaurant near Songshan Cultural and Creative Park, offering balanced dishes for guests who prefer lighter, wholesome dining.",
    "notes_ja": "松山文創園区近くの地中海風レストランです。バランスのよい料理や軽めのお食事を希望されるお客様におすすめです。"
  },
  {
    "map_label_name": "國立國父紀念館",
    "name_zh": "國立國父紀念館",
    "name_en": "National Dr. Sun Yat-Sen Memorial Hall",
    "name_ja": "国立国父紀念館",
    "primary_category": "景點",
    "subcategory": "古蹟",
    "business_type": "attraction",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.040030599999998,121.5602452",
    "address_zh": "110臺北市信義區仁愛路四段505號",
    "phone": "02 2758 8008",
    "opening_hours": "09:00 – 18:00",
    "near_mrt": "國父紀念館站",
    "notes": "國父紀念館腹地寬廣、視野開闊，可欣賞台北 101 與周邊城市景觀。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.040030599999998,121.5602452",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_011",
    "display_order": 11,
    "notes_zh": "國父紀念館腹地寬廣、視野開闊，可欣賞台北 101 與周邊城市景觀。",
    "notes_en": "The spacious grounds of the memorial hall offer open city views, including Taipei 101, and make a pleasant stop for sightseeing or a walk.",
    "notes_ja": "広々とした敷地から台北101を含む街並みを眺められます。観光や散歩の途中に立ち寄りやすいスポットです。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:31.462Z"
  },
  {
    "map_label_name": "誠品生活松菸",
    "name_zh": "誠品生活松菸",
    "name_en": "Eslite Spectrum Songyan",
    "name_ja": "誠品生活松菸店",
    "primary_category": "商店",
    "subcategory": "百貨",
    "business_type": "shop",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.044545,121.5614574",
    "address_zh": "110臺北市信義區菸廠路88號",
    "phone": "02 6636 5888",
    "opening_hours": "11:00 – 22:00",
    "near_mrt": "國父紀念館站",
    "notes": "結合書店、選物、展演與餐飲的百貨空間，適合逛街、買伴手禮或雨天備案。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.044545,121.5614574",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_012",
    "display_order": 12,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:35.344Z",
    "notes_zh": "結合書店、選物、展演與餐飲的百貨空間，適合逛街、買伴手禮或雨天備案。",
    "notes_en": "A lifestyle department store combining books, design goods, exhibitions, restaurants, and gift shopping, also useful as a rainy-day option.",
    "notes_ja": "書店、デザイン雑貨、展示、レストランがそろうライフスタイル型の商業施設です。お土産探しや雨の日の予定にも便利です。"
  },
  {
    "map_label_name": "BURGER OUT",
    "name_zh": "BURGER OUT",
    "name_en": "BURGER OUT",
    "name_ja": "BURGER OUT",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0431633,121.563065",
    "address_zh": "11072臺北市信義區忠孝東路四段553巷22弄2號",
    "phone": "02 2756 6860",
    "opening_hours": "11:30 – 14:30, 17:00 – 20:30",
    "near_mrt": "國父紀念館站",
    "notes": "美式漢堡專門店，份量實在、口味直接，適合想快速補充熱量的午晚餐。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0431633,121.563065",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_013",
    "display_order": 13,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:39.280Z",
    "notes_zh": "美式漢堡專門店，份量實在、口味直接，適合想快速補充熱量的午晚餐。",
    "notes_en": "A casual American-style burger spot with generous portions, convenient for a quick and satisfying lunch or dinner.",
    "notes_ja": "ボリュームのあるアメリカンスタイルのバーガー店です。手早くしっかり食べたいランチやディナーに便利です。"
  },
  {
    "map_label_name": "旬味 自然鍋物-台北美食 信義區美食 信義區火鍋 信義區火鍋推薦 信義區好吃推薦 信義區火鍋推薦 國父紀念館信義東區美食 台北大巨蛋美食 個人鴛鴦火鍋 火鍋美食",
    "name_zh": "旬味 自然鍋物-台北美食 信義區美食 信義區火鍋 信義區火鍋推薦 信義區好吃推薦 信義區火鍋推薦 國父紀念館信義東區美食 台北大巨蛋美食 個人鴛鴦火鍋 火鍋美食",
    "name_en": "旬味 自然鍋物-台北美食 信義區美食 信義區火鍋 信義區火鍋推薦 信義區好吃推薦 信義區火鍋推薦 國父紀念館信義東區美食 台北大巨蛋美食 個人鴛鴦火鍋 火鍋美食",
    "name_ja": "旬味 自然鍋物台北美食 信義区美食 信義区火鍋 信義区火鍋推薦 信義区好吃推薦 信義区高CP値火鍋鍋物 火鍋推薦 国父紀念館信義東区美食 台北大巨蛋美食 個人鴛鴦火鍋",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0405092,121.5626557",
    "address_zh": "110臺北市信義區逸仙路50巷18號",
    "phone": "02 2720 0873",
    "opening_hours": "星期一: 休息；星期二: 11:30 – 15:00, 17:30 – 21:00；星期三: 11:30 – 15:00, 17:30 – 21:00；星期四: 11:30 – 15:00, 17:30 – 21:00；星期五: 11:30 – 15:00, 17:30 – 21:00；星期六: 11:30 – 15:00, 17:30 – 21:00；星期日: 11:30 – 15:00, 17:30 – 21:00",
    "near_mrt": "國父紀念館站",
    "notes": "個人鍋物餐廳，主打自然湯底與鴛鴦鍋，適合想安靜吃火鍋的午晚餐。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0405092,121.5626557",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_014",
    "display_order": 14,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:43.171Z",
    "notes_zh": "個人鍋物餐廳，主打自然湯底與鴛鴦鍋，適合想安靜吃火鍋的午晚餐。",
    "notes_en": "An individual hot pot restaurant featuring natural broths and dual-flavor pots, ideal for a quieter lunch or dinner in the area.",
    "notes_ja": "自然なスープと二色鍋が特徴の一人鍋レストランです。周辺で落ち着いて火鍋を楽しみたい時に向いています。"
  },
  {
    "map_label_name": "嵩 sung 台北大安",
    "name_zh": "嵩 sung 台北大安",
    "name_en": "Sung (Taipei Da'an)",
    "name_ja": "Sung (Taipei Da'an)",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0430657,121.55575689999999",
    "address_zh": "106臺北市大安區延吉街131巷35號",
    "phone": "02 8772 0358",
    "opening_hours": "12:00 – 16:00, 17:00 – 23:30",
    "near_mrt": "國父紀念館站",
    "notes": "現代台菜餐廳，菜色精緻、適合聚餐，從大巨蛋周邊步行或短程車程可達。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0430657,121.55575689999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_015",
    "display_order": 15,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:46.856Z",
    "notes_zh": "現代台菜餐廳，菜色精緻、適合聚餐，從大巨蛋周邊步行或短程車程可達。",
    "notes_en": "A refined modern Taiwanese restaurant with polished presentation, suitable for a comfortable lunch or dinner gathering a short ride from Taipei Dome.",
    "notes_ja": "洗練された盛り付けのモダン台湾料理レストランです。台北ドーム周辺から短時間で行ける、ゆったりしたランチやディナーに適しています。"
  },
  {
    "map_label_name": "HANNA Pasta Café パスタ カフェ",
    "name_zh": "HANNA Pasta Café パスタ カフェ",
    "name_en": "HANNA Pasta Café パスタ カフェ",
    "name_ja": "HANNA Pasta Café パスタ カフェ",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.040281,121.56288939999999",
    "address_zh": "110臺北市信義區逸仙路42巷17號1樓",
    "phone": "02 8786 0518",
    "opening_hours": "11:30 – 15:30, 17:30 – 21:30",
    "near_mrt": "國父紀念館站",
    "notes": "日系風格義大利麵與咖啡餐廳，氛圍輕鬆，適合午餐、晚餐或聊天小聚。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.040281,121.56288939999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_016",
    "display_order": 16,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:50.582Z",
    "notes_zh": "日系風格義大利麵與咖啡餐廳，氛圍輕鬆，適合午餐、晚餐或聊天小聚。",
    "notes_en": "A relaxed Japanese-style pasta and cafe restaurant, suitable for lunch, dinner, coffee, or a casual catch-up.",
    "notes_ja": "日本風のパスタとカフェメニューを楽しめる落ち着いたレストランです。ランチ、ディナー、コーヒー休憩や軽い集まりに向いています。"
  },
  {
    "map_label_name": "東引快刀手 光復店 (必吃知名宵夜美食、平價麵館 滷味小吃)",
    "name_zh": "東引快刀手 光復店 (必吃知名宵夜美食、平價麵館 滷味小吃)",
    "name_en": "東引快刀手 光復店",
    "name_ja": "東引快刀手 光復店",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐|宵夜",
    "business_type": "restaurant",
    "meal_tags": [
      "宵夜"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0458164,121.5576116",
    "address_zh": "105臺北市松山區光復南路54號",
    "phone": "02 2577 7787",
    "opening_hours": "11:00 – 02:00",
    "near_mrt": "國父紀念館站",
    "notes": "在地人氣麵館與滷味小吃，價格親切，適合晚餐或活動後想吃熱食宵夜。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0458164,121.5576116",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_017",
    "display_order": 17,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:54.311Z",
    "notes_zh": "在地人氣麵館與滷味小吃，價格親切，適合晚餐或活動後想吃熱食宵夜。",
    "notes_en": "A popular local noodle shop serving simple, affordable noodles and braised snacks, convenient for dinner or a hot late-night bite after an event.",
    "notes_ja": "地元で人気の麺料理と滷味の小吃店です。手頃な価格で、夕食やイベント後の温かい夜食に便利です。"
  },
  {
    "map_label_name": "蘇阿姨比薩屋",
    "name_zh": "蘇阿姨比薩屋",
    "name_en": "Aunt Su's Pizza House",
    "name_ja": "Aunt Su's Pizza House",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0391419,121.5574355",
    "address_zh": "106臺北市大安區光復南路300號",
    "phone": "02 2740 2328",
    "opening_hours": "11:00 – 22:00",
    "near_mrt": "國父紀念館站",
    "notes": "老字號披薩店，適合多人分享，想吃美式披薩與炸物時很方便。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0391419,121.5574355",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_018",
    "display_order": 18,
    "notes_zh": "老字號披薩店，適合多人分享，想吃美式披薩與炸物時很方便。",
    "notes_en": "A long-running pizza restaurant suited to groups, especially for guests craving American-style pizza and fried sides.",
    "notes_ja": "長く親しまれているピザ店です。アメリカンスタイルのピザや揚げ物をグループで分けて楽しみたい時におすすめです。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:44:58.198Z"
  },
  {
    "map_label_name": "弘燁模型",
    "name_zh": "弘燁模型",
    "name_en": "弘燁模型",
    "name_ja": "弘燁模型",
    "primary_category": "商店",
    "subcategory": "其他",
    "business_type": "shop",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0433973,121.5636026",
    "address_zh": "110臺北市信義區忠孝東路四段553巷22弄55-1號",
    "phone": "02 2745 7722",
    "opening_hours": "13:00 – 21:00",
    "near_mrt": "市政府站",
    "notes": "模型與收藏品商店，適合對模型、玩具或周邊商品有興趣的旅客順逛。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0433973,121.5636026",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_019",
    "display_order": 19,
    "notes_zh": "模型與收藏品商店，適合對模型、玩具或周邊商品有興趣的旅客順逛。",
    "notes_en": "A model and collectibles shop for guests interested in hobby items, toys, or character merchandise while exploring the neighborhood.",
    "notes_ja": "模型やコレクションアイテムを扱うお店です。模型、玩具、キャラクターグッズに興味のあるお客様におすすめです。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:01.826Z"
  },
  {
    "map_label_name": "禾記茶餐廳大安店",
    "name_zh": "禾記茶餐廳大安店",
    "name_en": "Wokee Restaurant",
    "name_ja": "禾記茶餐庁大安店",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0396848,121.55633279999999",
    "address_zh": "106臺北市大安區光復南路280巷25號",
    "phone": "02 2778 1997",
    "opening_hours": "11:30 – 15:00, 17:00 – 22:00",
    "near_mrt": "國父紀念館站",
    "notes": "港式茶餐廳，供應燒臘、飯麵與港式飲品，適合快速又有飽足感的一餐。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0396848,121.55633279999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_020",
    "display_order": 20,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:05.762Z",
    "notes_zh": "港式茶餐廳，供應燒臘、飯麵與港式飲品，適合快速又有飽足感的一餐。",
    "notes_en": "A Hong Kong-style cha chaan teng serving roast meats, rice, noodles, and classic drinks, good for a quick and filling meal.",
    "notes_ja": "ロースト肉、ご飯もの、麺類、香港式ドリンクを楽しめる茶餐廳です。短時間でしっかり食べたい時に便利です。"
  },
  {
    "map_label_name": "宣牛溫體牛肉火鍋(光復店)",
    "name_zh": "宣牛溫體牛肉火鍋(光復店)",
    "name_en": "宣牛溫體牛肉火鍋(光復店)",
    "name_ja": "宣牛温体牛肉火鍋",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0391299,121.557025",
    "address_zh": "106臺北市大安區光復南路290巷5號",
    "phone": "02 2775 3232",
    "opening_hours": "12:00 – 21:30",
    "near_mrt": "國父紀念館站",
    "notes": "主打溫體牛肉火鍋，湯頭清甜、肉品新鮮，適合喜歡台式鍋物的聚餐。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0391299,121.557025",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_021",
    "display_order": 21,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:09.916Z",
    "notes_zh": "主打溫體牛肉火鍋，湯頭清甜、肉品新鮮，適合喜歡台式鍋物的聚餐。",
    "notes_en": "A Taiwanese fresh beef hot pot restaurant known for clear, naturally sweet broth and fresh beef, suitable for group dining.",
    "notes_ja": "新鮮な温体牛の火鍋を楽しめる台湾式の鍋料理店です。自然な甘みのある澄んだスープで、グループでのお食事にも向いています。"
  },
  {
    "map_label_name": "BaganHood 蔬食餐酒館",
    "name_zh": "BaganHood 蔬食餐酒館",
    "name_en": "BaganHood (Vegan Restaurant) -Taipei City Hall Station",
    "name_ja": "BaganHood (Vegan Restaurant) -Taipei City Hall Station",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0443206,121.5634869",
    "address_zh": "110臺北市信義區忠孝東路四段553巷46弄11號",
    "phone": "02 3762 2557",
    "opening_hours": "11:30 – 16:00, 17:00 – 22:00",
    "near_mrt": "市政府站",
    "notes": "蔬食餐酒館，菜色有設計感，適合素食者或想吃清爽無肉料理的聚會。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0443206,121.5634869",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_022",
    "display_order": 22,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:13.995Z",
    "notes_zh": "蔬食餐酒館，菜色有設計感，適合素食者或想吃清爽無肉料理的聚會。",
    "notes_en": "A stylish plant-based bistro with creative dishes, ideal for vegetarian guests or anyone looking for a lighter meat-free meal.",
    "notes_ja": "創意ある料理を提供するスタイリッシュなプラントベースのビストロです。ベジタリアンのお客様や軽めの食事を希望される方におすすめです。"
  },
  {
    "map_label_name": "地中海餐酒館 ABV Bar & Kitchen 台北光復店",
    "name_zh": "地中海餐酒館 ABV Bar & Kitchen 台北光復店",
    "name_en": "ABV Bar & Kitchen",
    "name_ja": "ABV Bar & Kitchen",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0401435,121.55568079999999",
    "address_zh": "106臺北市大安區光復南路260巷39號",
    "phone": "02 8771 8114",
    "opening_hours": "12:00 – 01:30",
    "near_mrt": "國父紀念館站",
    "notes": "地中海風格餐酒館，啤酒選擇多、餐點份量適中，適合晚餐與朋友小酌。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0401435,121.55568079999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_023",
    "display_order": 23,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:18.106Z",
    "notes_zh": "地中海風格餐酒館，啤酒選擇多、餐點份量適中，適合晚餐與朋友小酌。",
    "notes_en": "A Mediterranean-style bar and kitchen with a broad beer selection and shareable dishes, suitable for dinner or casual drinks with friends.",
    "notes_ja": "地中海風の料理と豊富なビールを楽しめるバー＆キッチンです。夕食や友人とのカジュアルな一杯に向いています。"
  },
  {
    "map_label_name": "臺灣銀行松山分行",
    "name_zh": "臺灣銀行松山分行",
    "name_en": "Bank of Taiwan Songshan Branch",
    "name_ja": "臺灣銀行 松山分行",
    "primary_category": "其他設施",
    "subcategory": "銀行",
    "business_type": "other",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0409492,121.5638165",
    "address_zh": "110臺北市信義區忠孝東路四段560號",
    "phone": "02 2729 3111",
    "opening_hours": "09:00 – 15:30",
    "near_mrt": "市政府站",
    "notes": "鄰近大巨蛋的銀行分行，可處理提款、換匯或臨時金融需求。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0409492,121.5638165",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_024",
    "display_order": 24,
    "notes_zh": "鄰近大巨蛋的銀行分行，可處理提款、換匯或臨時金融需求。",
    "notes_en": "A nearby Bank of Taiwan branch for ATM access, currency exchange, and other short-term banking needs during your stay.",
    "notes_ja": "台北ドーム近くの台湾銀行支店です。ATM、外貨両替、滞在中の一時的な金融手続きに便利です。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:21.685Z"
  },
  {
    "map_label_name": "CURISTA COFFEE奎士咖啡 市府旗艦店",
    "name_zh": "CURISTA COFFEE奎士咖啡 市府旗艦店",
    "name_en": "CURISTA COFFEE Taipei City Hall Shop",
    "name_ja": "CURISTA COFFEE Taipei City Hall Shop",
    "primary_category": "餐飲",
    "subcategory": "早餐|午餐|晚餐|咖啡",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐",
      "飲料"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.041588899999997,121.56405",
    "address_zh": "110臺北市信義區忠孝東路四段563號1樓",
    "phone": "02 2769 1668",
    "opening_hours": "07:30 – 20:00",
    "near_mrt": "市政府站",
    "notes": "空間明亮的咖啡店，供應咖啡、輕食與甜點，適合早餐、工作或短暫休息。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.041588899999997,121.56405",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_025",
    "display_order": 25,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:25.246Z",
    "notes_zh": "空間明亮的咖啡店，供應咖啡、輕食與甜點，適合早餐、工作或短暫休息。",
    "notes_en": "A bright cafe serving coffee, light meals, and desserts, suitable for breakfast, remote work, or a short break near Taipei City Hall.",
    "notes_ja": "明るい雰囲気のカフェで、コーヒー、軽食、デザートを提供しています。朝食、作業、台北市政府周辺での小休憩に便利です。"
  },
  {
    "map_label_name": "真芳碳烤吐司-信義創始店 台北早餐三明治",
    "name_zh": "真芳碳烤吐司-信義創始店 台北早餐三明治",
    "name_en": "Zhen Fang Brunch",
    "name_ja": "真芳碳烤吐司信義創始店 台北早餐三明治",
    "primary_category": "餐飲",
    "subcategory": "早餐",
    "business_type": "restaurant",
    "meal_tags": [
      "早餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.042463299999998,121.5642637",
    "address_zh": "110臺北市信義區忠孝東路四段559巷16弄17號",
    "phone": "02 2766 6766",
    "opening_hours": "06:30 – 13:30",
    "near_mrt": "市政府站",
    "notes": "信義區人氣碳烤吐司店，早餐時段很方便，適合外帶三明治與奶茶。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.042463299999998,121.5642637",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_026",
    "display_order": 26,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:29.287Z",
    "notes_zh": "信義區人氣碳烤吐司店，早餐時段很方便，適合外帶三明治與奶茶。",
    "notes_en": "A popular Xinyi breakfast shop known for charcoal-grilled toast, sandwiches, and milk tea, convenient for takeaway in the morning.",
    "notes_ja": "信義エリアで人気の炭火焼きトースト店です。朝のテイクアウトに便利で、サンドイッチやミルクティーが楽しめます。"
  },
  {
    "map_label_name": "年三十鐵板串燒居酒屋 光復店",
    "name_zh": "年三十鐵板串燒居酒屋 光復店",
    "name_en": "年三十鐵板串燒居酒屋 光復店",
    "name_ja": "年三十鉄板串焼居酒屋 光復店",
    "primary_category": "餐飲",
    "subcategory": "晚餐|宵夜",
    "business_type": "restaurant",
    "meal_tags": [
      "宵夜"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.038995,121.556083",
    "address_zh": "10694臺北市大安區光復南路308巷30號",
    "phone": "02 2771 1730",
    "opening_hours": "17:00 – 23:30",
    "near_mrt": "國父紀念館站",
    "notes": "鐵板串燒居酒屋，晚間氣氛熱鬧，適合活動後用餐或小酌續攤。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.038995,121.556083",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_027",
    "display_order": 27,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:33.049Z",
    "notes_zh": "鐵板串燒居酒屋，晚間氣氛熱鬧，適合活動後用餐或小酌續攤。",
    "notes_en": "A lively teppan skewer izakaya for evening dining, drinks, or a casual late-night stop after an event.",
    "notes_ja": "鉄板串焼きの居酒屋で、夜はにぎやかな雰囲気です。イベント後の食事や軽く一杯楽しみたい時に向いています。"
  },
  {
    "map_label_name": "鯛擔麵專賣店（台灣）—抱きしめ鯛",
    "name_zh": "鯛擔麵專賣店（台灣）—抱きしめ鯛",
    "name_en": "鯛担麵專賣店（台灣）—抱きしめ鯛",
    "name_ja": "鯛担面専売店（台湾）—抱きしめ鯛",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.040858,121.55448799999999",
    "address_zh": "106臺北市大安區延吉街108號",
    "phone": "02 2771 5921",
    "opening_hours": "11:30 – 20:30",
    "near_mrt": "國父紀念館站",
    "notes": "以鯛魚湯底拉麵為特色，口味細緻，適合想吃日式麵食的午晚餐。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.040858,121.55448799999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_028",
    "display_order": 28,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:37.117Z",
    "notes_zh": "以鯛魚湯底拉麵為特色，口味細緻，適合想吃日式麵食的午晚餐。",
    "notes_en": "A Japanese ramen shop featuring sea bream-based broth with a delicate flavor profile, suitable for lunch or dinner.",
    "notes_ja": "鯛だしのスープが特徴の日本式ラーメン店です。繊細な味わいで、ランチやディナーにおすすめです。"
  },
  {
    "map_label_name": "秦味館 Qin Wei Guan",
    "name_zh": "秦味館 Qin Wei Guan",
    "name_en": "Qin Wei Guan",
    "name_ja": "Qin Wei Guan",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0399226,121.5546196",
    "address_zh": "106臺北市大安區延吉街138巷2號",
    "phone": "02 8771 3288",
    "opening_hours": "11:30 – 14:30, 17:30 – 22:30",
    "near_mrt": "國父紀念館站",
    "notes": "陝西風味餐館，麵食與特色菜有辨識度，適合想換口味的聚餐選擇。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0399226,121.5546196",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_029",
    "display_order": 29,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:42.261Z",
    "notes_zh": "陝西風味餐館，麵食與特色菜有辨識度，適合想換口味的聚餐選擇。",
    "notes_en": "A Shaanxi-style restaurant with distinctive noodles and regional dishes, recommended for guests who would like to try something different.",
    "notes_ja": "陝西料理のレストランで、個性的な麺料理や郷土料理を楽しめます。少し違った味を試したいお客様におすすめです。"
  },
  {
    "map_label_name": "舞良麵 Dancing Noodles ｜東區必吃晚餐宵夜 延吉街 大巨蛋美食 無國界涼麵 麵飯（“不一樣乾麵”隔壁巷弄內）",
    "name_zh": "舞良麵 Dancing Noodles ｜東區必吃晚餐宵夜 延吉街 大巨蛋美食 無國界涼麵 麵飯（“不一樣乾麵”隔壁巷弄內）",
    "name_en": "舞良麵",
    "name_ja": "舞良面 Dancing Noodles ｜東区必吃晩餐宵夜 延吉街 大巨蛋美食 無国界涼面 面飯（“不一様乾面”隔壁巷弄内）",
    "primary_category": "餐飲",
    "subcategory": "晚餐|宵夜",
    "business_type": "restaurant",
    "meal_tags": [
      "宵夜"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0423062,121.5538876",
    "address_zh": "106臺北市大安區延吉街70巷5弄3號1樓",
    "phone": "02 8771 4450",
    "opening_hours": "18:00 – 01:30",
    "near_mrt": "國父紀念館站",
    "notes": "主打創意涼麵與麵飯料理，晚間營業，適合宵夜或想吃輕鬆小店時造訪。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0423062,121.5538876",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_030",
    "display_order": 30,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:45.755Z",
    "notes_zh": "主打創意涼麵與麵飯料理，晚間營業，適合宵夜或想吃輕鬆小店時造訪。",
    "notes_en": "A casual noodle shop specializing in creative cold noodles, rice, and noodle dishes, open in the evening for dinner or a light late-night meal.",
    "notes_ja": "創作涼麺やご飯・麺料理を提供するカジュアルなお店です。夜も営業しており、夕食や軽い夜食に便利です。"
  },
  {
    "map_label_name": "市府轉運站",
    "name_zh": "市府轉運站",
    "name_en": "Taipei City Hall Bus Station",
    "name_ja": "統聯客運",
    "primary_category": "交通",
    "subcategory": "轉運站",
    "business_type": "transport",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0404967,121.56478249999999",
    "address_zh": "110臺北市信義區忠孝東路五段6號",
    "phone": "02 8780 6252",
    "opening_hours": "05:00 – 01:00",
    "near_mrt": "市政府站",
    "notes": "信義區重要客運與公車轉運點，往返外縣市或轉乘市區交通都很方便。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0404967,121.56478249999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_031",
    "display_order": 31,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:49.728Z",
    "notes_zh": "信義區重要客運與公車轉運點，往返外縣市或轉乘市區交通都很方便。",
    "notes_en": "A major bus and coach terminal in Xinyi, convenient for intercity travel as well as transfers to local transportation.",
    "notes_ja": "信義区の主要なバス・長距離バスターミナルです。市外への移動や台北市内交通への乗り換えに便利です。"
  },
  {
    "map_label_name": "地一牛肉麵",
    "name_zh": "地一牛肉麵",
    "name_en": "Di Yi Beef Noodle Restaurant",
    "name_ja": "地一牛肉面",
    "primary_category": "餐飲",
    "subcategory": "晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0392007,121.5549147",
    "address_zh": "106臺北市大安區延吉街162號",
    "phone": "02 2775 5525",
    "opening_hours": "11:30 – 22:30",
    "near_mrt": "國父紀念館站",
    "notes": "牛肉麵店，適合晚餐時段來一碗熱湯麵，從大巨蛋周邊移動也不遠。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0392007,121.5549147",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_032",
    "display_order": 32,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:53.023Z",
    "notes_zh": "牛肉麵店，適合晚餐時段來一碗熱湯麵，從大巨蛋周邊移動也不遠。",
    "notes_en": "A beef noodle restaurant suitable for a warm, comforting dinner within easy reach of the Taipei Dome area.",
    "notes_ja": "台北ドーム周辺から行きやすい牛肉麺のお店です。夕食に温かく食べ応えのある一杯を楽しみたい時に向いています。"
  },
  {
    "map_label_name": "統一時代百貨 台北店",
    "name_zh": "統一時代百貨 台北店",
    "name_en": "Uni-ustyle",
    "name_ja": "Uni-ustyle",
    "primary_category": "商店",
    "subcategory": "百貨",
    "business_type": "shop",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0408461,121.5653962",
    "address_zh": "110臺北市信義區忠孝東路五段8號",
    "phone": "02 2729 9699",
    "opening_hours": "11:00 – 22:00",
    "near_mrt": "市政府站",
    "notes": "信義商圈大型百貨，餐飲、購物與轉乘機能完整，適合逛街或等候行程。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0408461,121.5653962",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_033",
    "display_order": 33,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:45:56.964Z",
    "notes_zh": "信義商圈大型百貨，餐飲、購物與轉乘機能完整，適合逛街或等候行程。",
    "notes_en": "A large department store in the Xinyi shopping district with dining, retail, and transit connections, useful for shopping or filling time between plans.",
    "notes_ja": "信義ショッピングエリアにある大型百貨店です。飲食、買い物、交通アクセスがそろい、予定の合間にも立ち寄りやすい施設です。"
  },
  {
    "map_label_name": "Taipei 101 Rainbow Walk",
    "name_zh": "Taipei 101 Rainbow Walk",
    "name_en": "Taipei 101 Rainbow Walk",
    "name_ja": "Taipei 101 Rainbow Walk",
    "primary_category": "景點",
    "subcategory": "其他",
    "business_type": "attraction",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.037855999999998,121.56327399999999",
    "address_zh": "Taipei City Hall, 市府路信義區臺北市110",
    "phone": "店家未提供",
    "opening_hours": "24 小時營業",
    "near_mrt": "市政府站",
    "notes": "彩虹地景步道鄰近市府與台北 101，適合拍照打卡並順遊信義商圈。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.037855999999998,121.56327399999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_034",
    "display_order": 34,
    "notes_zh": "彩虹地景步道鄰近市府與台北 101，適合拍照打卡並順遊信義商圈。",
    "notes_en": "A colorful rainbow walkway near Taipei City Hall and Taipei 101, popular for quick photos and easy to combine with a visit to the Xinyi district.",
    "notes_ja": "台北市政府と台北101の近くにあるカラフルなレインボーウォークです。写真撮影や信義エリア散策と合わせて楽しめます。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:46:00.493Z"
  },
  {
    "map_label_name": "一品 花 雕 雞 市民旗艦店",
    "name_zh": "一品 花 雕 雞 市民旗艦店",
    "name_en": "一品 花 雕 雞 市民旗艦店",
    "name_ja": "一品 花 凋 鶏 市民旗艦店",
    "primary_category": "餐飲",
    "subcategory": "晚餐|宵夜",
    "business_type": "restaurant",
    "meal_tags": [
      "晚餐",
      "宵夜"
    ],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0446973,121.55273779999999",
    "address_zh": "105臺北市松山區市民大道四段207號",
    "phone": "02 2570 0388",
    "opening_hours": "17:00 – 01:00",
    "near_mrt": "國父紀念館站",
    "notes": "主打花雕雞與熱炒料理，口味濃郁，適合多人晚餐或宵夜聚餐。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0446973,121.55273779999999",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_035",
    "display_order": 35,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:46:05.093Z",
    "notes_zh": "主打花雕雞與熱炒料理，口味濃郁，適合多人晚餐或宵夜聚餐。",
    "notes_en": "A restaurant specializing in Huadiao chicken and Taiwanese stir-fried dishes, best for flavorful group dinners or a late-night meal.",
    "notes_ja": "花雕雞と台湾式炒め料理を中心としたレストランです。味のしっかりした料理を楽しむグループディナーや夜食に向いています。"
  },
  {
    "map_label_name": "國家鐵道博物館",
    "name_zh": "國家鐵道博物館",
    "name_en": "National Railway Museum",
    "name_ja": "国家鉄道博物館",
    "primary_category": "景點",
    "subcategory": "古蹟",
    "business_type": "attraction",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0474346,121.5647175",
    "address_zh": "110臺北市信義區市民大道五段50號",
    "phone": "02 8787 8850",
    "opening_hours": "09:30 – 17:00",
    "near_mrt": "市政府站",
    "notes": "由舊鐵道場域轉型的博物館，適合了解台灣鐵道文化與歷史建築。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0474346,121.5647175",
    "is_active": true,
    "walk_10min_from_hotel": true,
    "id": "ihg_036",
    "display_order": 36,
    "notes_zh": "由舊鐵道場域轉型的博物館，適合了解台灣鐵道文化與歷史建築。",
    "notes_en": "A museum transformed from a historic railway site, offering a look at Taiwan's railway culture, industrial heritage, and preserved architecture.",
    "notes_ja": "歴史ある鉄道施設を活用した博物館です。台湾の鉄道文化、産業遺産、保存建築に触れられます。",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:46:08.641Z"
  },
  {
    "map_label_name": "博仁綜合醫院",
    "name_zh": "博仁綜合醫院",
    "name_en": "Pojen General Hospital",
    "name_ja": "博仁総合医院",
    "primary_category": "其他設施",
    "subcategory": "醫院",
    "business_type": "other",
    "meal_tags": [],
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=25.0499097,121.5576835",
    "address_zh": "105臺北市松山區光復北路66號",
    "phone": "02 2578 6677",
    "opening_hours": "24 小時營業",
    "near_mrt": "國父紀念館站",
    "notes": "鄰近大巨蛋與光復南路的綜合醫院，可作為旅途中臨時醫療需求參考。",
    "source_status": "map_only",
    "source_url": "https://www.google.com/maps/search/?api=1&query=25.0499097,121.5576835",
    "is_active": true,
    "walk_10min_from_hotel": false,
    "id": "ihg_037",
    "display_order": 37,
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:46:11.270Z",
    "notes_zh": "鄰近大巨蛋與光復南路的綜合醫院，可作為旅途中臨時醫療需求參考。",
    "notes_en": "A general hospital near Taipei Dome and Guangfu South Road, useful as a reference point for urgent medical needs during travel.",
    "notes_ja": "台北ドームと光復南路の近くにある総合病院です。旅行中に急な医療対応が必要な場合の参考になります。"
  },
  {
    "map_label_name": "漢堡排 嘉 GARDEN CITY遠東大巨蛋店",
    "name_zh": "漢堡排 嘉 GARDEN CITY遠東大巨蛋店",
    "name_en": "Hamburg Yoshi Taipei Dome",
    "name_ja": "Hamburg Yoshi Taipei Dome",
    "primary_category": "餐飲",
    "subcategory": "午餐|晚餐",
    "business_type": "restaurant",
    "meal_tags": [
      "午餐",
      "晚餐"
    ],
    "google_maps_url": "https://maps.app.goo.gl/3izmi8rsERCJwmVX6",
    "address_zh": "110臺北市信義區忠孝東路四段515號",
    "phone": "店家未提供",
    "opening_hours": "11:30 – 22:00",
    "near_mrt": "國父紀念館站",
    "notes": "日式漢堡排定食餐廳，適合午晚餐；炭火香氣明顯，建議留意衣物氣味。",
    "source_status": "map_only",
    "source_url": "https://maps.app.goo.gl/3izmi8rsERCJwmVX6",
    "is_active": true,
    "walk_10min_from_hotel": false,
    "id": "ihg_038",
    "display_order": 38,
    "notes_zh": "日式漢堡排定食餐廳，適合午晚餐；炭火香氣明顯，建議留意衣物氣味。",
    "notes_en": "A Japanese hamburger steak set-meal restaurant for lunch or dinner; the charcoal aroma can be noticeable, so guests may want to plan accordingly.",
    "notes_ja": "",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:39:18.883Z"
  },
  {
    "map_label_name": "武蔵野森珈琲Diner",
    "name_zh": "武蔵野森珈琲Diner",
    "name_en": "Musashino Mori Coffee Far Eastern Garden City Shop",
    "name_ja": "Musashino Mori Coffee Far Eastern Garden City Shop",
    "primary_category": "餐飲",
    "subcategory": "早餐|咖啡",
    "business_type": "restaurant",
    "meal_tags": [
      "早餐",
      "咖啡"
    ],
    "google_maps_url": "https://maps.app.goo.gl/iapMK3uza9L43Nb17",
    "address_zh": "110臺北市信義區忠孝東路四段515號",
    "phone": "0227686118",
    "opening_hours": "07:30 – 22:00",
    "near_mrt": "國父紀念館站",
    "notes": "日系咖啡 Diner，供應早餐、咖啡與輕食，適合早晨或午後休息。",
    "source_status": "map_only",
    "source_url": "https://maps.app.goo.gl/iapMK3uza9L43Nb17",
    "is_active": true,
    "walk_10min_from_hotel": false,
    "id": "ihg_039",
    "display_order": 39,
    "notes_zh": "日系咖啡 Diner，供應早餐、咖啡與輕食，適合早晨或午後休息。",
    "notes_en": "A Japanese-style coffee diner serving breakfast, coffee, and light meals, suitable for a relaxed morning or afternoon break.",
    "notes_ja": "",
    "category": "",
    "lat": 0,
    "lng": 0,
    "updated_at": "2026-05-14T15:39:22.881Z"
  }
];
